# This file is a placeholder.
# The actual users.db.sql content is generated by setup.sh and injected with cryptographic flags.
# Do not edit this file — it will be overwritten during deployment.
PLACEHOLDER=true
